import java.util.InputMismatchException;
import java.util.Scanner;

public class test78 {
    public static void main(String[] args) {
        //int a=10;
        Scanner s=new Scanner(System.in);
        //int a=s.nextInt();
        //int b=s.nextInt();
        //int arr[]={12,34,56,78,90};
        //int index=s.nextInt();
        /*try{
            //System.out.println(args[2]);
           // System.out.println(a/0);
            int a=s.nextInt();
            int b=s.nextInt();
            int arr[]={12,34,56,78,90};
            int index=s.nextInt();
            System.out.println(a/b);
            System.out.println(arr[index]);
        }*/
        //try{
          //  return;
        //}
        try{
            System.exit(0);
        }
        finally{
            System.out.println("in finally block");} //in this case finally block will not print;*/
//        try{
//            throw new ArithmeticException("/ by zero");
//        }
//        catch(ArithmeticException obj){
//            System.out.println(obj);
//        }
        //catch(Exception E){//it will create error

        //}
        //catch (ArrayIndexOutOfBoundsException obj){
           // System.out.println(obj);
        //}
        /*catch(ArithmeticException | ArrayIndexOutOfBoundsException | InputMismatchException obj){
            System.out.println(obj);
        }*/
       // finally{
           // System.out.println("in finally block");
       /// }
        //catch(ArithmeticException obj){
        //obj.printStackTrace();
    //}

        /*catch(Exception obj){
            System.out.println(obj);
        }*/
        /*catch(ArithmeticException | ArrayIndexOutOfBoundsException | InputMismatchException | EXception obj){
            System.out.println(obj);  //IT WILL PRINT ERROR AS WE CANT DEFINE PARENT CLASS as exception in this upside
        }*/
        //System.out.println("end of the main");
    }

}
